repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: Run Ruff linter
        args: ["--fix"]
        entry: uv run ruff check
        language: python
        types: [python]
        pass_filenames: true
        always_run: true

      - id: ruff-format
        name: Run Ruff formatter
        entry: uv run ruff format
        language: system
        types: [python]
        pass_filenames: true
        always_run: true
